Repository d-h-k/sidedish, pull requests merged in 2021-04, with the labels that each got.

#14 메인 카테고리 Mockup API
  BE/side-dish-backend/src/main/java/com/codesquad/team14/controller/ItemController.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/domain/Badge.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/domain/Category.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/domain/Item.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/domain/Order.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/domain/User.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/dto/ItemDto.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/repository/ItemRepository.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/service/ItemService.java
Labels: enhancement, 백엔드

#19 [BE] 카테고리 DTO 생성 및 유틸 패키지 분리
  BE/side-dish-backend/src/main/java/com/codesquad/team14/domain/Category.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/domain/Item.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/dto/DetailedItemDto.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/dto/ItemDto.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/dto/category/CategoryDto.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/dto/item/DetailedItemDto.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/dto/item/ItemDto.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/repository/CategoryRepository.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/utils/Badge.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/utils/DeliveryType.java
Labels: 백엔드

#53 [BE] 카테고리 생성
  BE/side-dish-backend/src/main/java/com/codesquad/team14/controller/CategoryController.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/controller/ItemController.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/domain/Category.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/domain/Item.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/dto/CategoryDto.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/repository/CategoryRepository.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/repository/ItemRepository.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/service/CategoryService.java
  BE/side-dish-backend/src/main/java/com/codesquad/team14/service/ItemService.java
  BE/side-dish-backend/src/main/resources/schema.sql
  BE/side-dish-backend/src/test/java/com/codesquad/team14/SideDishBackendApplicationTests.java
Labels: 백엔드

#57 Fix 절대경로 상대경로로 수정하기 #48
  FE/jsconfig.json
  FE/src/App.js
  FE/src/Components/Carousel/CarouselContainer.js
  FE/src/Components/Carousel/CarouselNavigator/CarouselButton.js
  FE/src/Components/Carousel/CarouselNavigator/DefaultNavigator.js
  FE/src/Components/Carousel/CarouselNavigator/UpperNavigatior.js
  FE/src/Components/Carousel/CarouselNavigator/index.js
  FE/src/Components/Carousel/index.js
  FE/src/Components/Header/Header.js
  FE/src/Components/Header/Navigation/Navigation.js
  FE/src/Components/Header/SearchBar/SearchBar.js
  FE/src/Components/Modal/BottomSide/BottomSide.js
  FE/src/Components/Modal/DetailProductModal.js
  FE/src/Components/Modal/LeftSide/LeftSide.js
  FE/src/Components/Modal/LeftSide/SmallThumbnail.js
  FE/src/Components/Modal/RightSide/CountSelector.js
  FE/src/Components/Modal/RightSide/RightSide.js
  FE/src/Components/Tabs/Tabs.js
  FE/src/Components/commons/Card.js
  FE/src/Pages/MainPage/MainDish/index.js
  FE/src/Pages/MainPage/Tabs/index.js
  FE/src/Pages/MainPage/index.js
  FE/src/index.js
Labels: 프론트엔드

#58 Fix: Card Tabs분기처리 fix #51
  FE/src/Components/Modal/BottomSide/BottomSide.js
  FE/src/Components/Tabs/Tabs.js
  FE/src/Components/commons/Cards/TabCard.js
  FE/src/Components/commons/Cards/index.js
  FE/src/Pages/MainPage/MainDish/index.js
Labels: 프론트엔드

#67 Fix: error 처리 useReducer로 수정 fix #50
  FE/src/Components/Header/Dropdown/Dropdown.js
  FE/src/Components/Header/Navigation/Navigation.js
  FE/src/Components/Modal/DetailProductModal.js
  FE/src/Components/Modal/LeftSide/SmallThumbnail.js
  FE/src/Components/Modal/RightSide/Prices.js
  FE/src/Components/Modal/RightSide/RightSide.js
  FE/src/Components/Modal/RightSide/Sum.js
  FE/src/Components/Tabs/Tabs.js
  FE/src/Components/commons/Cards/TabCard.js
  FE/src/Components/commons/Cards/index.js
  FE/src/Pages/MainPage/index.js
  FE/src/images/loading.gif
  FE/src/util/API.js
  FE/src/util/reducer.js
Labels: 프론트엔드

#77 Feat: useAsync 함수 구현 fix #50
  FE/src/Components/Modal/DetailProductModal.js
  FE/src/Components/Tabs/Tabs.js
  FE/src/Components/commons/Cards/TabCard.js
  FE/src/Components/commons/Cards/index.js
  FE/src/Pages/MainPage/index.js
  FE/src/util/hooks/useAsync.js
Labels: 프론트엔드
